name: file_slave
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  grpc:     ^3.0.2
  async:    ^2.9.0
  protobuf: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test:  ^1.16.0
