version: "3.9"
services:
  # BROKER SERVICE ---------------------------------------------
  broker:
    image: eclipse-mosquitto:latest
    # General configuration --------------
    container_name: broker
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    # Deployment configuration -----------
    deploy:
      mode: global
      restart_policy: 
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  # FILE MASTER ------------------------------------------------
  filemaster:
    image: 10.1.2.114:5000/master
    build: ./Master
    # General configuration --------------
    environment:
      IP_HOST: broker
    depends_on:
      - broker
    # Deployment configuration -----------
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  # NODE FILE SLAVE --------------------------------------------
  node-slave:
    image: 10.1.2.114:5000/node-slave
    build: ./fs-node
    # General configuration --------------
    environment:
      IPSERVER: filemaster
      FOLDER: /proc
    depends_on:
      - filemaster
    # Deployment configuration -----------
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==worker"

  # DART FILE SLAVE --------------------------------------------
  dart-slave:
    image: 10.1.2.114:5000/dart-slave
    build: ./Dart-FileSlave
    # General configuration --------------
    environment:
      SERVER_IP: filemaster
    depends_on:
      - filemaster
    # Deployment configuration -----------
    deploy:
      replicas: 2
      restart_policy: 
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        constraints: 
          - "node.role==worker"
