version: "3.9"
services:
  # BROKER SERVICE ---------------------------------------------
  broker:
    image: eclipse-mosquitto:latest
    # General configuration --------------
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    # Deployment configuration -----------
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  # FILE MASTER ------------------------------------------------
  file-master:
    image: 10.1.2.114:5000/master
    build: ./Master
    # General configuration --------------
    ports:
      - 50051:50051
    env_file:
      - master.env
    # Deployment configuration -----------
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  # NODE FILE SLAVE --------------------------------------------
  node-slave:
    image: 10.1.2.114:5000/node-slave
    build: ./fs-node
    # General configuration --------------
    env_file:
      - node_slave.env
    # Deployment configuration -----------
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==worker"

  # DART FILE SLAVE --------------------------------------------
  dart-slave:
    image: 10.1.2.114:5000/dart-slave
    build: ./Dart-FileSlave
    # General configuration --------------
    env_file:
      - dart_slave.env
    # Deployment configuration -----------
    deploy:
      replicas: 2
      restart_policy: 
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        constraints: 
          - "node.role==worker"
